[package]
name = "ivan-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["macros", "json"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
anyhow = "1"
thiserror = "1"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }
tokio-cron-scheduler = "0.15"
chrono-tz = "0.10"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono", "macros", "migrate"] }
tera = {version = "2", features = ["glob_fs"]}
chrono = { version = "0.4.45", features = ["serde"] }
lettre = { version = "0.11", default-features = false, features = [
    "smtp-transport", "pool", "builder", "hostname",
    "tokio1", "tokio1-rustls-tls",
] }
dashmap = "6"
uuid = { version = "1", features = ["v4"] }
quick-xml = { version = "0.37", features = ["serialize"] }
rust_xlsxwriter = "0.96"